server:
  port: 8067

spring:
  cloud:
    gateway:
      routes:
        - id: student-module-api
          uri: lb://STUDENT_MODULE
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

jwt:
  secret: cGF2YW5pdHNvbHV0aW9uc2tleQ==

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info,refresh
