server:
  port: 8067

spring:
  cloud:
    gateway:
      routes:
        - id: student-module-api
          uri: lb://STUDENT_MODULE
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

        - id: uploads-direct
          uri: http://localhost:8081
          predicates:
            - Path=/uploads/**

        - id: static-files
          uri: http://localhost:8081
          predicates:
            - Path=/**.html,/**.css,/**.js,/**.png,/**.jpg,/**.jpeg,/**.ico,/

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
