server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: student-module
          uri: lb://STUDENT-MODULE
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

        - id: uploads
          uri: http://localhost:8081
          predicates:
            - Path=/uploads/**

        - id: static-files
          uri: http://localhost:8081
          predicates:
            - Path=/**.html,/**.css,/**.js,/**.png,/**.jpg,/**.ico

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
