server:
  port: 8067

spring:
  cloud:
    gateway:
      routes:
        # 1. ALL API CALLS → Student Module (Eureka + Load Balancer)
        - id: student-module-api
          uri: lb://student-module                # ← 100% CORRECT
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # 2. PDF & Uploads direct (no auth needed)
        - id: uploads-direct
          uri: http://localhost:8081
          predicates:
            - Path=/uploads/**

        # 3. Static files (login page, css, js, images)
        - id: static-files
          uri: http://localhost:8081
          predicates:
            - Path=/**.html,/**.css,/**.js,/**.png,/**.jpg,/**.jpeg,/**.ico,/

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info,metrics
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
