spring:
  application:
    name: student-module

  datasource:
    url: jdbc:mysql://localhost:3306/studentsdata?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Pspk#@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ppspk7263@gmail.com
    password: ljts mlxi xafi cofo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true

  sql:
    init:
      mode: never

  boot:
    admin:
      client:
        url: http://localhost:9090      # Admin Server URL
        instance:
          prefer-ip: false
          service-url: http://localhost:8081

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false            # 🚀 DO NOT use LAN IP
    hostname: localhost                 # 🚀 Force Eureka to use localhost
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"                    # 🚀 Show all endpoints
  endpoint:
    health:
      show-details: always              # 🚀 Required for Admin Server
