# File name must be: student-module.yml   (exactly this name, no extra folder)
spring:
  application:
    name: Student_Module

  # --------------------- DATABASE CONFIG ---------------------
  datasource:
    url: jdbc:mysql://localhost:3306/studentsdata?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Pspk#@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # --------------------- EMAIL CONFIG (Gmail) ---------------------
  mail:
    host: smtp.gmail.com
    port: 587
    username: ppspk7263@gmail.com
    password: ljts mlxi xafi cofo   # Your Gmail App Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true   # Change to false in production

  # --------------------- DISABLE data.sql ---------------------
  sql:
    init:
      mode: never

# --------------------- SERVER PORT ---------------------
server:
  port: 8081
